name: 'imsamdez/actions.merge-branch'
description: 'Merge a branch into another'
author: 'samdez'
inputs:
  base:
    required: true
    description: 'Branch that will welcome the merge'
  compare:
    required: true
    description: 'Branch to merge'
  wait_for_ci:
    required: false
    description: 'Action will wait for CI on compare branch before merging'
    default: true
  github_token:
    required: true
    description: 'A github token'
runs:
  using: 'node12'
  main: 'dist/index.js'
